Tests
BuildForSDG/team-013-Backend pull request #9
Opened 2020-05-14 10:35 UTC by anje123

## Description
Please include a summary of the change and relevant motivation and context. 
I wrote the tests for the teacher endpoints

List any dependencies that are required for this change.
supertest

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added necessary inline code documentation
- [x] I have added tests that prove my fix is effective and that this feature works
- [x] New and existing unit tests pass locally with my changes

2020-05-14 15:16 UTC, jioblack commented
Nice work

2020-05-14 15:17 UTC, jioblack submitted a review, later dismissed
Nice work

2020-05-14 17:13 UTC, Theshedman requested changes

2020-05-14 17:13 UTC, Theshedman commented on src/index.js
> +module.exports = server;
You should not export the server. The one to use for testing is the app.js

2020-05-14 17:13 UTC, Theshedman commented on __tests__/teacher.test.js
> +import app from '../src/index';
If you look closely you will notice that we have app.js different from index.js while we do that was to separate express app from the express server. So you don't need to import the server. 
 Instead, what you should import is the express app from app.js.

2020-05-14 17:13 UTC, Theshedman commented on __tests__/teacher.test.js
> +    .post('/api/teachers')
Please don't use main database for testing. It will corrupt the data in the database. You have two options to go about it. You can mock the data and not talk to database again. Or you can create a test database that we can use for testing which you have to setup and teardown before and after each test respectively

2020-05-14 17:31 UTC, anje123 commented on __tests__/teacher.test.js
> +    .post('/api/teachers')
you can use any database you want in your test environment,  just set the mongo_uri to the database

2020-05-14 17:34 UTC, anje123 commented on __tests__/teacher.test.js
> +    .post('/api/teachers')
the tests create a user then after all the tests it deletes it.

2020-05-14 17:37 UTC, anje123 commented on __tests__/teacher.test.js
> +    .post('/api/teachers')
and also on the delete all teacher endpoint , will there be any case we will need to delete all teachers

2020-05-14 17:41 UTC, Theshedman commented on __tests__/teacher.test.js
> +    .post('/api/teachers')
> you can use any database you want in your test environment, just set the mongo_uri to the database

That's what I am saying. You should create a test db and reference the url (mongo_url) for use while testing. Or you can mock the data and don't have to talk to the db

2020-05-14 17:43 UTC, Theshedman commented on __tests__/teacher.test.js
> +    .post('/api/teachers')
> and also on the delete all teacher endpoint , will there be any case we will need to delete all teachers

Not likely. Just provided it should the need arise. But it's definitely unlikely to happen

2020-05-15 09:42 UTC, Theshedman approved these changes

2020-05-15 09:52 UTC, alexzender45 approved these changes
Nice one bro

2020-05-15 13:31 UTC, taiwosunday99 approved these changes
Job well done..This test has resolved the issue #7

2020-05-15 13:32 UTC, merged